[tool.poetry]
name = "digital-archive"
version = "0.1.0"
description = "Tools for the Digital Archive Project at Aarhus Stadsarkiv"
authors = ["Nina Jensen <jnik@aarhus.dk>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.7"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
