[tool.poetry]
name = "digiarch"
version = "0.9.22"
description = "Tools for the Digital Archive Project at Aarhus Stadsarkiv"
authors = ["Aryan Muhammadi Landi <arml@aarhus.dk>", "Nina Jensen <jnik@aarhus.dk>", "Aarhus Stadsarkiv <stadsarkiv@aarhus.dk>"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://stadsarkiv.aarhus.dk/"
repository = "https://github.com/aarhusstadsarkiv/digiarch"
keywords = ["archiving", "preservation", "identification"]
include = ["pyproject.toml"]

[tool.poetry.dependencies]
python = "^3.8"
click = ">=7,<9"
tqdm = "^4.36"
dacite = "^1.0"
python-dateutil = "^2.8.1"
natsort = ">=7.0.1,<9.0.0"
requests = "^2.23.0"
pydantic = "^1.6.1"
sqlalchemy = "~1.3"
databases = {extras = ["sqlite"], version = ">=0.3.2,<0.5.0"}
acamodels = "^0.5.3"
sqlalchemy_utils = ">=0.36.8,<0.39.0"
pypng = "^0.0.21"
Pillow = ">=8.3.2,<10.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
pytest-cov = "^3.0"
mypy = "^0.812"
black = "^23.1"

flake8 = "^4.0.1"
pytest-asyncio = "^0.18.1"
freezegun = "^1.1.0"

[tool.poetry.scripts]
digiarch = "digiarch.cli:cli"

[tool.black]
line-length = 79
exclude = ".venv"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
asyncio_mode="strict"
pythonpath = ["."]

