[tool.poetry]
name = "digital_archive"
version = "0.2.3"
description = "Tools for the Digital Archive Project at Aarhus Stadsarkiv"
authors = ["Nina Jensen <jnik@aarhus.dk>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^0.25.1"
click = "^7.0"
python-magic = "^0.4.15"
tqdm = "^4.36"
dacite = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8"
mypy = "^0.730.0"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
flake8 = "^3.7"

[tool.poetry.scripts]
digiarch = "digital_archive.digiarch:cli"

[tool.black]
line-length = 79

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

