---
# Python CircleCI 2.1 configuration using Poetry

version: 2.1
commands:
  # Initialises the docker image and updates dependencies using poetry
  init:
    steps:
      # Get current code base
      - checkout

      - run:
          name: Install Python dependencies
          # Install dependencies using poetry. This looks at the poetry.lock
          # file and installs new dependencies only when updates occur.
          command: poetry install

jobs:
  format:
    docker:
      - image: circleci/python:3.7
    steps:
      - init
      # Check formatting using Black via Poetry
      - run:
          name: test dir
          command: ls -a
      - run:
          name: Check formatting using Black
          command: poetry run black --check digital-archive/
          # command: |
          #   poetry run black --check digital-archive/
          #   poetry run black --check tests/

  # lint:
  #   docker:
  #     - image: circleci/python:3.7
  #   steps:
  #     - init
  #     # Check linting using flake8 via Poetry
  #     - run:
  #         name: Check linting using flake8
  #         command: |
  #           poetry run flake8 digital-archive/
  #           poetry run flake8 tests/

workflows:
  version: 2.1
  development:
    jobs:
      - format
      # - lint
