# Python CircleCI 2.1 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      # Get current code
      - checkout 
      # Install poetry
      - run
        name: install poetry
        command: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      # Install Python dependencies using poetry
      - run 
        name: install py deps
        command: poetry install
