---
# Python CircleCI 2.1 configuration using Poetry

version: 2.1

orbs:
  # Use the codecov orb for code coverage reports
  codecov: codecov/codecov@1.0.5

commands:
  # Initialises the docker image and updates dependencies using poetry
  init:
    steps:
      # Get current code base
      - checkout
      # Restore cache
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      # Install dependencies using poetry.
      - run:
          name: Initialse Poetry config
          command: |
            poetry config
      - run:
          name: Install Python dependencies
          command: poetry install
      # Save to cache
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

jobs:
  check:
    docker:
      - image: circleci/python:3.7
    steps:
      - init
      # Check formatting using Black
      - run:
          name: Check formatting using Black
          command: |
            poetry run black --check digiarch/
            poetry run black --check tests/
      # Check linting using flake8
      - run:
          name: Check linting using flake8
          command: |
            pip install flake8 --user --quiet
            flake8 digiarch/
            flake8 tests/
      # Check types using mypy via Poetry
      - run:
          name: Check types using mypy
          command: |
            poetry run mypy digiarch/
            poetry run mypy tests/
      # Check code using Prospector via Poetry
      - run:
          name: Check code using Prospector
          command: |
            poetry run prospector -M digiarch/
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - init
      # Install sf which is used for identification
      - run:
          name: "Install sf (siegfried)"
          command: |
            wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
            echo "deb http://dl.bintray.com/siegfried/debian wheezy main" | sudo tee -a /etc/apt/sources.list
            sudo apt update && sudo apt install siegfried
            
      # Run tests, generate coverage report
      - run:
          name: Test and generate report using pytest with coverage
          command: |
            poetry run pytest --cov=digiarch --cov-report=xml
      # Upload coverage to codecov
      - codecov/upload:
          file: coverage.xml
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - init
      # Build digiarch with Poetry
      - run:
          name: Build sdist and wheel with Poetry
          command: poetry build
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - init
      # Test that git tag conforms to project version
      - run:
          name: Test git tag vs. version
          command: |
            sh .circleci/check_version.sh
      - run:
          name: Publish to PyPI
          command: |
            poetry publish --build -u jnik-aarhus -p $pypi_pwd

workflows:
  version: 2.1
  development:
    jobs:
      - check
      - test
      - build
  release:
    jobs:
      - check:
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - deploy:
          requires:
            - check
            - test
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
