# Python CircleCI 2.1 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout # Get current code
      - run # Installs poetry
        name: install poetry
        command: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      - run # Installs Python dependencies using poetry
        name: install py deps
        command: poetry install
