# Python CircleCI 2.1 configuration using Poetry
version: 2.1
jobs:

  build:

    docker:
      - image: circleci/python:3.7 
    steps:

      - checkout 
      - restore_cache:
          keys:
            - deps-{{checksum "poetry.lock"}}
      - run: 
          name: Install Python Dependencies
          command: poetry install
      - save_cache:
          key: deps-{{checksum "poetry.lock"}}
          paths: 
            - /home/circleci/.cache/pypoetry/virtualenvs