# Python CircleCI 2.1 configuration using Poetry
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout 
      - run:
          name: Install Poetry
          command: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      - run: 
          name: Install Python Dependencies
          command: poetry install