name: Deploy

on:
<<<<<<< HEAD
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  check:
    name: Check version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: Run check_version.sh
        run: sh .github/check_version.sh
        
  deploy:
    name: Deploy to PyPI
=======
  release:
    tags:
      - 'v*.*.*'
  push:
    tags:
      - 'v*'
jobs:   
  build:
    name: Build wheel
>>>>>>> master
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up poetry
        uses: snok/install-poetry@v1.1.1
      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry install
<<<<<<< HEAD
      - name: Build wheel
        run: poetry build
=======
      - name: Build project
        run: poetry build
>>>>>>> master
