name: Build Wheels

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  wheel:
    name: Build Wheels
    runs-on: ubuntu-latest
    if: ${{ github.ref_name }} == "master"
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: uv sync --all-extras --dev
      - name: Get Tag
        id: tag
        run: echo "tag=$(git tag -l --sort=-version:refname | head -1)" >> "$GITHUB_OUTPUT"
      - name: Get Changelog
        run: python .github/workflows/get_changelog.py CHANGELOG.md "${{ steps.tag.outputs.tag }}" > release.md
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          body_path: release.md
          files: |
            wheels.zip
