name: Build Wheels

on:
  push

env:
  PYTHON_VERSION: 3.9.18
  POETRY_VERSION: 1.6.1

jobs:
  wheel:
    name: Build Wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build Wheels
        run: python -m pip wheel -w dist .
      - name: Save Wheels
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
