name: Tag

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  tag:
    if: github.event.pull_request.merged == true
    name: Add Version Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read_version.outputs.version }}
      tag_exists: ${{ steps.tag_exists.outputs.tag_exists }}
    steps:
      - uses: actions/checkout@v4
      - name: Read Version
        id: read_version
        run: |
          version="$(grep --color=never 'version *= *".*"' pyproject.toml)"
          version="${version%\"}"
          version="${version#*\"}"
          version="${version#v}"
          echo "version=v$version" >> "$GITHUB_OUTPUT"
      - name: Check if Tag Exists
        id: tag_exists
        env:
          VERSION: ${{ steps.read_version.outputs.version }}
        run: |
          tag="$(git tag | grep --color=never "${VERSION//./\.}")"
          if [[ "$tag" = "$VERSION" ]]; then echo "tag_exists=true" >> "$GITHUB_OUTPUT"
          else echo "tag_exists=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Add Tag
        if: ${{ steps.tag_exists.outputs.tag_exists }} == "false"
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.read_version.outputs.version }}",
              sha: context.sha
            })

