name: Tests

on: [pull_request]

jobs:
  call-linting-from-utils:
    uses: aarhusstadsarkiv/acautils/.github/workflows/linting.yml@073c8a34410576650737df4e711ea0dbd94d5713

  test:
    name: Run tests & get coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up poetry
        uses: snok/install-poetry@v1.1.0
      - name: Set up go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'
      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry install
      - name: Install siegfried
        run: |
          go install github.com/richardlehane/siegfried/cmd/sf@latest
          sf -update
      - name: Test and generate coverage report
        run: |
          poetry run pytest --cov=digiarch --cov-report=xml
      - name: Upload to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
