name: Linting & Test

on:
  push:
    paths:
      - digiarch/**
      - tests/**
      - pyproject.toml
      - poetry.lock
      - .github/workflows/test.yml

env:
  PYTHON_VERSION: 3.11.5
  POETRY_VERSION: 1.6.1

jobs:
  linting:
    name: Check Linting & Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - run: poetry install
      - name: ruff check
        run: poetry run ruff check digiarch
      - name: ruff format
        run: poetry run ruff format --check digiarch

  version:
    name: Test Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          project_name="$(grep --color=never 'name *= *".*"' pyproject.toml)"
          project_name="${project_name%\"}"
          project_name="${project_name#*\"}"
          version_project="$(grep --color=never 'version *= *".*"' pyproject.toml)"
          version_project="${version_project%\"}"
          version_project="${version_project#*\"}"
          version_package="$(grep --color=never '__version__ *= *".*"' "$project_name"/__version__.py)"
          version_package="${version_package%\"}"
          version_package="${version_package#*\"}"
          test "$version_project" = "$version_package" || exit $?
          grep -E "## v$version_project"'( .*)?$' CHANGELOG.md || exit $?

  version-acacore:
    name: Test acacore Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Fetch Acacore Version
        run: |
          acacore_remote="$(python -c 'import urllib.request,json;print(json.loads(urllib.request.urlopen("https://api.github.com/repos/aarhusstadsarkiv/acacore/tags").read())[0]["name"])')"
          acacore_remote="${acacore_remote#v}"
          acacore_package="$(grep 'acacore =' pyproject.toml | grep -oE 'tag[ ]*=[ ]*"[^"]+"')"
          acacore_package="${acacore_package#*\"}"
          acacore_package="${acacore_package#v}"
          acacore_package="${acacore_package%\"}"
          test "$acacore_remote" = "$acacore_package"

  version-database:
    name: Test database version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test database version
        run: |
          acacore_database="$(sqlite3 tests/files/_metadata/files.db "select value from Metadata where key = 'version'")"
          acacore_package="$(grep 'acacore =' pyproject.toml | grep -oE 'tag[ ]*=[ ]*"[^"]+"')"
          acacore_package="${acacore_package#*\"}"
          acacore_package="${acacore_package#v}"
          acacore_package="${acacore_package%\"}"
          test "$acacore_database" = "$acacore_package"
          

  pytest:
    name: pytest
    needs: version-database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - uses: actions/setup-go@v4
      - run: poetry install
      - run: go install github.com/richardlehane/siegfried/cmd/sf@latest
      - name: Unit test
        env:
          GOPATH: /home/runner/go
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report -m --fail-under=80 --skip-empty --skip-covered
